version: '3.8'
services:
  frontend-prod:
    build: .
    image: padaria-frontend:prod
    container_name: padaria-frontend-prod
    ports:
      - "4173:80"
    restart: always
    networks:
      - padaria_net

networks:
  padaria_net:
    external: true
    name: panificadora_padaria_net
